[package]
name = "rfc"
version = "0.1.0"
authors = ["Casey Robinson <casey@rampantmonkey.com>", "Scott Steele <scottlsteele@gmail.com>"]

[[bin]]
name = "rfc"
path = "src/main.rs"

[dependencies]
regex = "0.1"
docopt = "0.6.72"
time = "0.1"
